import rtconfig
from building import *

Import('SDK_LIB')

cwd = GetCurrentDir()

src = Glob('src/*.c')

path = [cwd + '/include']

group = DefineGroup('tl_app', src, depend = [''], CPPPATH = path)

Return('group')
